### ISSUE TITLE
site fora do ar

### ISSUE THREAD

**Issue by lcharles123** [marcelodive/compleaks#2]
O site http://compleaks.ijunior.com.br/ esta fora do ar, poderiam corrigir isso por favor? obrigado.

**Comment by marcelodive** [comment]
Bom dia, @lcharles123 
Faz muito tempo que não tenho acesso ao sistema interno da Ijúnior, então não teria como subir a aplicação novamente. O código que está neste repositório deve funcionar, mas está muito desatualizado.
Acredito que seria um exercício interessante reimplementar o compleaks com melhores práticas.
